# Generated by Django 5.0.8 on 2024-09-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogindexpage_blogpagegalleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='image',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
    ]
